### ISSUE TITLE
Table in tutorial displays wrong

### ISSUE THREAD

**Issue by raiph** [masak/007#39]
From tutorial page:

feature Perl 6 007 Python

braces yes yes no user-defined operators yes yes no variable declarations yes yes no macros yes yes no implicit typecasts yes no no sigils yes no no multis yes no no implicit returns yes no no

**Comment by masak** [comment]
Thank you for noticing. 06f326c fixes the table in the tutorial in the simplest way possible.

Before closing this issue I'd like to

- [ ] Explore using [Github Flavored Markdown tables](https://help.github.com/articles/github-flavored-markdown/#tables)
- [ ] Explore using HTML tables (in case GFM tables aren't good enough of don't convert easily)
- [ ] Unbreak the conversion script, which currently would produce a `pre code` thing instead of a nicely colored table

**Comment by masak** [comment]
[GH tables](https://github.com/masak/007/commit/035d936f6caf2f7d3a0957f19f551aa832a72898) render nicely; I didn't need to make any changes to the conversion script because they also convert nicely.

Closing.
