### ISSUE TITLE
division

### ISSUE THREAD

**Issue by claes-magnus** [masak/007#438]
I don't know if this already is discussed somewhere, but - if not - why not use the infix-functionality and include division? Sure, without floats uneven numbers will always be rounded. But hey! Isn't better than nothing?

This code 'rounds' to the nearest integer before:
```
func infix:</>(v1,v2) {
  my tempVal = v1;
  my count = 0;

  while (tempVal >= v2) {
    tempVal = tempVal - v2;
    count = count + 1;
  }
  return count;
}
say(9/3); # 3
say(19/3); # 6
say(145/3); # 48
say(932/75); # 12
```

**Comment by masak** [comment]
First off, let me just say how lovely it is that a newcomer to the language files an issue with a custom operator already attached. :smile:

@claes-magnus There's a division operator already; it's called `divmod`. It does everything your `infix:</>` does, except it's not `O(v1 / v2)`, it works correctly for negative operands too, it doesn't loop infinitely for division by 0, and _it also returns information about the remainder_.

```
$ bin/007 -e='say(9 divmod 3); say(19 divmod 3); say(145 divmod 3); say(932 divmod 75)'
(3, 0)
(6, 1)
(48, 1)
(12, 32)
```

The discussion on why we don't have an `infix:</>` in the language is captured in [this comment](https://github.com/masak/007/issues/34#issuecomment-147200158) (though you can safely skip the bit on pattern matching). Back in 2015 I still didn't know we wanted tuples in the language, so `divmod` was not really an option. We got tuples in June this year, and `infix:<divmod>` in July. :smile:

I believe this is the best we can do with only integers. Python 2 shows that providing `infix:</>` for only integers is _confusing_, because data is literally lost. Python 3 goes one better and Huffmanizes flooring division to `infix:<//>` while making `infix:</>` consistently keep all precision.

I expect us to provide an `infix:</>` operator in connection with having either a rational-type module or a double-type module. But we'll have to examine the design space around that separately for those modules.

Cheers! 🥂 Closing.
