### ISSUE TITLE
issues --> possibilities (don't know if this is an issue) :)

### ISSUE THREAD

**Issue by claes-magnus** [masak/007#519]
I love your reflections. When you're done you should edit, make a 'process document' that includes the best parts, and your discussions. @masak's reflections (I think that Carl is the main vehicle when it comes to reflections in this project) and his discussions with @vendethiel and others. 

My contention is that this would be valuable to others. Perhaps it could be included in some kind of 'history'/'process' section at the project homepage? 

Another idea would be  - ok, perhaps I'm stretching it now/again - to write 'a how to write a compiler' text and link to the different issues, so the reader can get a sense of (possible) problems, complications (issues) and so on. The main advantage would that the reader would  see, 'meet' 'real' problems. 

I think this would be particularly good for junior developers who don't grasp the whole process of writing a compiler, get a sense of 'real' issues (or how to put it). Often 'tutorials' or even whole books are way to 'easy'; you're provided with a solution, not the problems... and this is not always helpful. What *not* to do, is often equally important as what you *should* do (at least, I think, to the beginner programmer).

Who knows what lovely and cool spin-offs would emerge from such a procedure? It would be a truly **honest** project. And from honesty emerges the possibility to close in on truth, I would say.

Anyhow! I love reading your discussions and reflections.

**Comment by masak** [comment]
Re **process document**: thank you for the kind words. I think you will enjoy the planned fallout of the #401 documentation and also https://github.com/masak/007/issues/415#issuecomment-434622308 &mdash; basically, my plan is to document for each language-extending module what _forces_ went into shaping that feature the way it is, comparing and contrasting with alternatives.

Re **"how to write a compiler" tutorial**: I like the idea. As you're aware, there's [a book](https://github.com/masak/compiler-book) in the very early stages. But your idea sounds like something smaller/earlier than that &mdash; maybe even something that can serve as an early version/prototype of the book. Being a fan of [getting results early](https://medium.com/@bre/the-cult-of-done-manifesto-724ca1c2ff13), I approve/agree. It will by necessity be a separate effort/project out-of-scope from 007, but of course we can link to the resulting post(s) from here.

Closing this issue due to its overlap with existing things.
